name: MemeTools
main: st.northw.memetools.MemeTools
version: 1.2-SNAPSHOT
api-version: 1.13
author: nwradio
commands:
  mt:
    description: This is the main MemeTools command
    usage: /mt
    permission: MemeTools.mt
    permission-message: You don't have permission to use MemeTools
  chatspam:
    description: This spams broadcasts to the chat... Use wisely!
    usage: /chatspam
    permission: MemeTools.cs
    permission-message: You don't have permission to use ChatSpam
  lightningbolt:
    description: lightning bolt arrow!
    usage: /lightningbolt
    permission: MemeTools.lb
    permission-message: You don't have permission to use LightningBolt
  mtbc:
    description: simple broadcast to accompany chatspam
    usage: /mtbc
    permission: MemeTools.mtbc
    permission-message: You don't have permission to use mtbc
permissions:
  MemeTools.*:
    description: Gives access to all meme commands